### ISSUE TITLE
Does This Support Syslog TCP

### ISSUE THREAD

**Issue by tigerpeng2001** [scriptingislife/graylog-content-pack-nginx-syslog#1]
I am looking for a good way to send logs from Nginx to Graylog.
Just forked your work and plan to work on it. 
I'd know if this support Syslog TCP input, if not what could be the best way to set it up?

**Comment by scriptingislife** [comment]
Hello,

The syslog feature of NGINX only supports UDP. If you want to send logs over TCP you'll need to use a separate log forwarder like rsyslog.

https://nginx.org/en/docs/syslog.html

https://serverfault.com/questions/770280/nginx-log-to-syslog-on-tcp-port
